---
title: "KAS_level"
author: "Gayoung Park"
date: "10/29/2018"
output: html_document
---

```{r setup, include=FALSE}
suppressMessages(library(tidyverse))

#data from PhD data sheet, not KAS sheet.
mydata  <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRBTqiIHQP1Pg3De1IGsJgVFiJla1dIHyHsGEsSmel8WVAeXXXHmSiyNnQAad9ATdzeukS43WE3PZ2m/pub?gid=0&single=true&output=csv")

#dafa from KAS data sheet.
kasr <- read.csv ("https://docs.google.com/spreadsheets/d/e/2PACX-1vQQ9zhSCHjt-1qdSLltD1rhEI_DmaIKtah5yA9WWlsB0gGJWMOYltZR71r00NgkfaYz8YH392oZOWPu/pub?gid=1950751706&single=true&output=csv")

```

I just wanted to make a plot for elevation of each site, and show is there is a relationship between the time of first occupation and elevation, and whether or not there are stemmed points.

We can see that 


```{r}
mydata_ages <- 
  mydata %>% 
  separate(C14.BP., into = c('age', 'error'),
          sep = "±") %>% 
  mutate(age_ka = parse_number(age) / 1000,
         error = parse_number(error)) %>% 
  mutate(has_sp = ifelse(!is.na(SP.), "yes", "no"))

ggplot(mydata_ages, 
       aes(x = age_ka,
           y = altitude.m._of_main_layer,
       color = as.factor(has_sp))) +
  geom_point() +
  xlab("Age of occupation (ka)") +
  ylab("Elevation above sea level (m)") +
  geom_smooth(se = FALSE) +
  theme_minimal(base_size = 16)
```


Using raw material information sheeet from KAS data sheets. I don't know how to import whole sheets with multiple sub-sheets. I need to use other sheets too.

```{r}
ggplot(kasr, 
       aes(X)) +
  geom_histogram() +
  xlab("Site name") +
  ylab("Raw material type")

```